name: vac_card
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cawaf_api:
    git:
      url: git@github.com:MustaineWT/cawaf_services_api.git
      path: ./cawaf_api
  provider: ^6.0.1
  get_it: ^7.2.0
  dartz: ^0.10.0
  equatable: ^2.0.2
  logger: ^1.0.0
  qr_code_scanner: ^0.6.1
  shared_preferences: ^2.0.9
  google_sign_in: ^5.2.1
  url_launcher: ^6.0.17
  geolocator: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - google.png
    - profile.png
